In [3]:
import numpy as np
import pandas as pd

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [7]:
from google.colab import files
uploaded = files.upload()

Saving covid_toy.csv to covid_toy (1).csv

In [13]:
df = pd.read_csv('covid_toy.csv')

In [25]:
df.head()

# fever -> Imputation
# cough -> Ordinal Encoding
# gender -> One Hot Encoding
# city -> One Hot Encoding
# has_covid -> Label Encoding

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [14]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [17]:
X_train

    age  gender  fever   cough       city
4    65  Female  101.0    Mild     Mumbai
9    64  Female  101.0    Mild      Delhi
24   13  Female  100.0  Strong    Kolkata
84   69  Female   98.0  Strong     Mumbai
96   51  Female  101.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
53   83    Male   98.0    Mild      Delhi
76   80    Male  100.0    Mild  Bangalore
11   65  Female   98.0    Mild     Mumbai
42   27    Male  100.0    Mild      Delhi

[80 rows x 5 columns]

# 1. Aam Zindagi

In [26]:
# adding simple imputer to fever col (Mean Values filled)
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [27]:
# OrdinalEncoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [32]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [36]:
# Extracting Age
X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns = ['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [39]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis = 1)

# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis = 1)

X_train_transformed.shape

(80, 7)

# 2. Mentos Zindagi

In [40]:
from sklearn.compose import ColumnTransformer

In [47]:
# passthrough -> just don't do anything to untouched Columns
# drop -> just removed the untouched Columns

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [49]:
# fit -> Learning or Training on train data.

transformer.fit_transform(X_train).shape

(80, 7)

In [51]:
transformer.transform(X_test).shape

(20, 7)